### ISSUE TITLE
生成不了Linux agent

### ISSUE THREAD

**Issue by wcxxxxx** [jm33-m0/emp3r0r#124]
![image](https://user-images.githubusercontent.com/43629256/162140114-be829385-bb17-4996-94ca-69843585ff91.png)

**Comment by jm33-m0** [comment]
I wonder why you think it failed, since your screenshot indicates otherwise...

**Comment by jm33-m0** [comment]
In case you ask again, check `agent_2022xxx.exe` and see if the file works
