### ISSUE TITLE
get command unable to download file with spaces in its name

### ISSUE THREAD

**Issue by iriscot** [jm33-m0/emp3r0r#136]
Considering this framework have so many cool features, it's a shame it cannot handle spaces in filenames! Quotes and slash-escaping doesn't help. The command just shows usage when the filename with spaces passed as argument:

```
get File with spaces.bin
get <remote path>
```

**Comment by jm33-m0** [comment]
Thanks for reporting, I will work on a fix

**Comment by jm33-m0** [comment]
Now `get` can handle file paths with spaces, but not yet for `mv`, `cp` and `put`. I will consider supporting `\ ` or quotes in future versions.

**Comment by jm33-m0** [comment]
![image](https://user-images.githubusercontent.com/10167884/172556677-3a50843d-e9c8-4a44-9fa7-51f08ecb5306.png)

@iriscot Now emp3r0r supports `'` quoted and `\` escaped commands, if you find any bugs with my implementation, please open a new issue.
