### ISSUE TITLE
Tor not working?

### ISSUE THREAD

**Issue by xxlimit** [jm33-m0/emp3r0r#145]
I am currently running Ubuntu 22.04 LTS

The CC only asks for the tor sever.
But when I run tor sever as the port I still don't get any connections. 
![image](https://user-images.githubusercontent.com/66466672/177885372-0b6e54e6-6660-4e4d-92ae-ac9411a2b505.png)

**Comment by jm33-m0** [comment]
Well it's simple, if you don't specify a Tor proxy, it will use `socks5://127.0.0.1:9050` as default, which is unavailable, as shown in your screenshot.

**Comment by jm33-m0** [comment]
To use a Tor proxy you only need a properly configured hidden service and a Tor proxy on agent side.

See [wiki](https://github.com/jm33-m0/emp3r0r/wiki/Getting-started) for details.

Also a statically linked `tor` binary can be found in the repo, you can use it to provide Tor proxy.

**Comment by xxlimit** [comment]
I have the tor sever setup with it the problem is for some reason the tor sever isn't responding.
What should the tor sever config look like?

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/emp3r0r/wiki/Getting-started#tor
