### ISSUE TITLE
Emp3r0r console pane dead

### ISSUE THREAD

**Issue by taibaiyifeng** [jm33-m0/emp3r0r#151]
![图片](https://user-images.githubusercontent.com/12912903/182375815-e217471f-0f86-44d6-9cb6-5d335fd10dba.png)

**Comment by taibaiyifeng** [comment]
![图片](https://user-images.githubusercontent.com/12912903/182376156-e46126b8-2082-4ebd-81b2-bb54e5b173ef.png)

**Comment by jm33-m0** [comment]
需要提供完整的traceback信息及复现步骤，最好是文字形式
