### ISSUE TITLE
windows 的type命令无效

### ISSUE THREAD

**Issue by c0okB** [jm33-m0/emp3r0r#157]
获取windows权限后，执行type命令查看文本信息，type命令无效
<img width="456" alt="image" src="https://user-images.githubusercontent.com/57324119/188791207-1dba3527-9d46-4cb8-9e61-8be1878cc125.png">

**Comment by jm33-m0** [comment]
`type`是一个cmd shell的命令而不是内置程序（所以不存在`type.exe`)，不像Linux环境中的`cat`，emp3r0r默认只能执行`%PATH%`中已有的程序。

如果shell窗口可用的话，建议使用shell窗口。

**Comment by jm33-m0** [comment]
如有疑问可以继续留言，issue暂时关闭

**Comment by jm33-m0** [comment]
I used to implement `cmd.exe /C` in emp3r0r Windows version, but then I found it's unnecessary and quite alarming for anti-virus.
