### ISSUE TITLE
Remote shell: encoding problems

### ISSUE THREAD

**Issue by c0okB** [jm33-m0/emp3r0r#158]
执行系统命令，比如systeminfo 返回的是中文乱码

**Comment by jm33-m0** [comment]
这是正常现象，因为Windows中文版使用GBK编码，而Linux环境下的终端默认使用UTF-8编码。所以这不是emp3r0r的问题，你手工将终端编码调成相应的就可以显示了。

**Comment by jm33-m0** [comment]
In case someone needs it, I am adding translation: When you see encoding error, try to change the default encoding setting of your terminal (for example `gnome-shell`), emp3r0r is not responsible for decoding those characters, it just bring them in and your terminal prints them.
