### ISSUE TITLE
问题2

### ISSUE THREAD

**Issue by c0okB** [jm33-m0/emp3r0r#159]
1，文件上传的方法是将文件传到临时的web目录下，web目录是公开可访问的？
2，没法生成linux的马，gen_agent 选定type 1，还是生成exe

**Comment by jm33-m0** [comment]
兄弟，issue不是聊天，标题要改成有意义的。

> 文件上传的方法是将文件传到临时的web目录下，web目录是公开可访问的？

请自行测试

> 没法生成linux的马，gen_agent 选定type 1，还是生成exe

`.exe`只是一个后缀名，不代表它是PE文件，请不要被误导，此问题已被问过多次

**Comment by jm33-m0** [comment]
> 文件上传的方法是将文件传到临时的web目录下，web目录是公开可访问的？

针对这个问题如果你需要进一步评论请新开issue

**Comment by c0okB** [comment]
我测过了，上传文件到临时的web目录下，你的代码有小问题，直接拼接文件绝对路径到www/后面了，会导致本地文件找不到，并且文件上传到目标机器上后，www目录下的临时文件，没有自动删除。假如C2部署在公网，岂不是所有人都能访问得到。

**Comment by jm33-m0** [comment]
> 假如C2部署在公网，岂不是所有人都能访问得到

如果你把全路径送给别人，他们就可以访问到。你是直接复制的log链接访问吗？如果是的话你应该会注意到这个路径不是那么容易被人获取的。

> 你的代码有小问题，直接拼接文件绝对路径到www/后面了，会导致本地文件找不到

我没看懂你的意思，另外请新开issue或者修改本issue的标题
