### ISSUE TITLE
Agent Daemon Error

### ISSUE THREAD

**Issue by Error996** [jm33-m0/emp3r0r#18]
```
[root@vultr shm]# ./emp3r0r -cdnproxy "wss://example.com/path/to/websocket/server" -daemon
emp3r0r agent has started
2021/03/07 14:23:33 Testing if agent is alive...
2021/03/07 14:23:33 Seems dead: dial unix /dev/shm/.246d895/.s6Y4tDtahIuL: connect: connection refused
2021/03/07 14:23:33 Failed to kill old emp3r0r os: process already finished
2021/03/07 14:23:33 /dev/shm/.246d895/.s6Y4tDtahIuL exists, testing connection...
2021/03/07 14:23:33 Testing if agent is alive...
2021/03/07 14:23:33 Seems dead: dial unix /dev/shm/.246d895/.s6Y4tDtahIuL: connect: connection refused
```
But
`./emp3r0r -cdnproxy "wss://example.com/path/to/websocket/server"`
this is ok

![20210307222732](https://user-images.githubusercontent.com/12880110/110243319-beeca800-7f94-11eb-8353-5320a4a2e36e.png)

**and by the way,how to correct use libemp3r0r ????**

**Comment by jm33-m0** [comment]
`-daemon` option seems buggy, I will look into it.

> and by the way,how to correct use libemp3r0r ????

libemp3r0r is experimental, it can be used independently. You will need to modify the source a little bit to meet your need.

**Comment by jm33-m0** [comment]
Fixed, please `git pull` and rebuild the agent
