### ISSUE TITLE
Need Custom Agent Tag

### ISSUE THREAD

**Issue by Error996** [jm33-m0/emp3r0r#19]
Need Custom Agent Tag Or Add Custom Agent Label

Because once the Agent exceeds a certain number, it will be difficult to identify

Good Job

**Comment by jm33-m0** [comment]
Yeah it would be nice to have custom tagging, I will try to implement it in `build.py` so we can name each agent on its birth.

**Comment by Error996** [comment]
yep,or add a lable like vultr.com

**Comment by Error996** [comment]
Lable exists on CC, it is better to set on CC,Just suggest

**Comment by jm33-m0** [comment]
> Lable exists on CC, it is better to set on CC,Just suggest

Then we need a file to record `label -> UUID` mapping, and a set of commands to update the file. Sounds like a lot more work to do, I will try to implement the mapping file first. Thanks for the advice.

**Comment by Error996** [comment]
i have an other question,dose CC Indicator must be "emp3r0r" ????

**Comment by jm33-m0** [comment]
Yeah, for now it's `emp3r0r`. But with HTTPS, there's no need to change this value, they will be encrypted anyway.

**Comment by Error996** [comment]
I modified and used libemp3r0r.so, but all files have been hidden, but the process can still be seen, whether it is ps -ef or netstat -anptl
![20210308135151](https://user-images.githubusercontent.com/12880110/110280319-96f15900-8015-11eb-9ba1-1c294a81541c.png)
![20210308135225](https://user-images.githubusercontent.com/12880110/110280333-9a84e000-8015-11eb-9d92-0bbaaeebf23a.png)
![20210308135247](https://user-images.githubusercontent.com/12880110/110280349-a07ac100-8015-11eb-86b7-f67a72987005.png)

**Comment by Error996** [comment]
![20210308135436](https://user-images.githubusercontent.com/12880110/110280474-d6b84080-8015-11eb-8798-6ae9a6a1fba8.png)

**Comment by Error996** [comment]
sorry，i konw how

**Comment by jm33-m0** [comment]
Okay, next time open a new issue instead.

**Comment by jm33-m0** [comment]
Fixed in https://github.com/jm33-m0/emp3r0r/commit/e23d7c1c5132f73340fc6580a5a7dc3e8b93b8d7
