### ISSUE TITLE
Multi-Arch support for Linux

### ISSUE THREAD

**Issue by Q1ngShan** [jm33-m0/emp3r0r#191]
Is it possible to add options to templates for different system architectures, such as ARM for Linux when using gen_agent
<img width="590" alt="image" src="https://user-images.githubusercontent.com/24487351/231666134-e6f0c2b3-deef-4b7b-9b09-b7b8f51a723a.png">

**Comment by jm33-m0** [comment]
Sure thing, I will add it in the next release

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/emp3r0r/commit/40bc0fe9e123eac5842a32c6af5d3facc56c0ebf

**Comment by jm33-m0** [comment]
Now (almost) every possible architecture (`GOARCH`) supported by Go is supported by emp3r0r (linux). For Windows targets you can use either `386` or `amd64`.
