### ISSUE TITLE
`run_proxy` throws port_fwd error

### ISSUE THREAD

**Issue by jm33-m0** [jm33-m0/emp3r0r#192]
Here's the error:

![](https://user-images.githubusercontent.com/31686398/231676583-b725a030-4ffe-4b41-af24-14c38517f8e9.PNG)

**Comment by jm33-m0** [comment]
Tested on TOR transport which has very low quality connection, this error can be reproduced. I also discovered that `get file` feature fails at 99% progress.

**Comment by zqd233** [comment]
I think I found the reason :( 
It is my mistake
I set autoproxy feature to N
Enable autoproxy feature (will enable UDP broadcasting)? [y/N] 

That's why I can not use autoproxy 

Thanks a lot for answer

**Comment by jm33-m0** [comment]
I will test again with broadcasting on, but I doubt it's the reason

**Comment by jm33-m0** [comment]
@zqd233 You are right, the root cause of this issue is socks proxy server is not running on agent side. I am pushing a fix in the next release.
