### ISSUE TITLE
tmux ui issues

### ISSUE THREAD

**Issue by opensesamedoors** [jm33-m0/emp3r0r#199]
1)  when I execute ls_targets command, file tmux.go line 270  ------>       err := ioutil.WriteFile(pane.TTY, []byte(msg), 0777) does not works on ubuntu 22,it prints nothing but when I change this line to CliPrint("%s",msg),it works.
2)  when I execute target n,it works first time in tmux "Shell 2" panel,but when I execute target n second time,it show /dev/shm/.xxxxxxxxxxxxxxxxxxxxxx file can not find,so Shell 2 panel close and in dead status.

**Comment by jm33-m0** [comment]
Thanks for reporting. For the second issue you can try with latest release, it should be solved.

The first one needs further investigation, I will give you details later.
