### ISSUE TITLE
libemp3r0r's bug

### ISSUE THREAD

**Issue by Error996** [jm33-m0/emp3r0r#20]
There is a bug in libemp3r0r, when libemp3r0r is loaded,the file will not disappear, but the name will become blank

![20210308141639](https://user-images.githubusercontent.com/12880110/110282247-1fbdc400-8019-11eb-9e78-626ca418e803.png)

**Comment by jm33-m0** [comment]
That's weird, maybe it has something to do with your terminal?

Also, it hides the parent directory, excluding the children items, unless they have the `HIDE_ME` pattern in their filenames.

**Comment by Error996** [comment]
agent:/dev/shm/emp3r0r
agent's dir:/dev/shm/.45dd5
agent's id file:/dev/shm/.45dd5/emp3r0r_pids
libemp3r0r.so:/dev/shm/.45dd5/libemp3r0r.so
maybe something is wrong with me

**Comment by Error996** [comment]
but i have another tool to hide it,include ip
https://github.com/Error996/bdvl
I just want to be lazy, one tool for all functions

**Comment by jm33-m0** [comment]
libemp3r0r has been deprecated, the plan is to focus on the C2 framework itself, libraries and kernel modules can be modified to work with emp3r0r if desired
