### ISSUE TITLE
Not getting target !

### ISSUE THREAD

**Issue by FreeRealease** [jm33-m0/emp3r0r#214]
I use portmap.io to portforward i changed inside the json file the port and when i generate agent and run the .exe on my main I dont get it listed there ... 
In setting i use for x64  as for my pc and tried diferent combinationations but still i dont get the connection..  Please help

**Comment by FreeRealease** [comment]
Even tried the tor method but still not getting a connection

**Comment by jm33-m0** [comment]
> I use portmap.io to portforward i changed inside the json file the port

What portmap.io and what port?

> Even tried the tor method but still not getting a connection

Of course it won't get you a connection, tor is not designed to magically connect your agents

**Comment by jm33-m0** [comment]
If you can't clearly explain what you need help with or it's not related to this project in any way, this issue can be closed.
