### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by picos13** [jm33-m0/emp3r0r#215]
when i install emp3r0r gives me this ERROR, cp: cannot stat 'stub*': No such file or directory
[ERROR] stub

[ERROR] install failed

**Comment by jm33-m0** [comment]
How did you install? Did you read the documents?

**Comment by jm33-m0** [comment]
And please, if you can't describe what happened, use a screenshot or just copy the output and format it properly with Github's markdown editor.
