### ISSUE TITLE
The same IP address cannot go online repeatedly?

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#227]
# Describe the bug

The same IP address cannot go online repeatedly?

# To Reproduce

gen_agent  
linux  amd64
Set Shadowsocks + KCP  

Client  A  (ip x.x.x.x1)  Download and execution the Agent.  
Client  B   (ip x.x.x.1)  Download and execution the Agent.

On Targets Page Shwo,  
All Target show From ip is My emp3r0r Server IP。 (Same IP , different process and port)
Exit the emp3r0r,  and reopen, A host cannot go online.  Aother host cannot execute commands. Procedure

# other help
After selecting target 0, how do I exit to the home page, Instead of quitting the app

**Comment by jm33-m0** [comment]
There's nothing wrong with `from` IP, it's expected to be your local IP since you are using Shadowsocks in KCP tunnel.

>  Exit the emp3r0r, and reopen, A host cannot go online. Aother host cannot execute commands. Procedure

Show me the logs from those two hosts. You can see log with `VERBOSE=true`

**Comment by jm33-m0** [comment]
> After selecting target 0, how do I exit to the home page, Instead of quitting the app

You don't need to "exit to home page", there's no such thing as "home page". If you want to work on a different host, just type `target 1/2/3` and it will switch.

**Comment by winezer0** [comment]
> Show me the logs from those two hosts. You can see log with VERBOSE=true

I don't know how to read log files. 

Two client processes have been killed, I' need  retest them

**Comment by winezer0** [comment]
> > After selecting target 0, how do I exit to the home page, Instead of quitting the app
> 
> You don't need to "exit to home page", there's no such thing as "home page". If you want to work on a different host, just type `target 1/2/3` and it will switch.

how to clean up all command window records of the previous target.

**Comment by winezer0** [comment]
I ran the running test again, and it's OK now.



![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/3a7f8a2e-e588-4a7f-9cbb-1b0ea3ecd5a3)

**Comment by winezer0** [comment]
> I ran the running test again, and it's OK now.

The "port occupied" problem in the upper right corner may be unexpected

**Comment by jm33-m0** [comment]
> I ran the running test again, and it's OK now.

That's good to know

> how to clean up all command window records of the previous target.

This is not implemented, I think it's necessary that you keep a record of command history

> The "port occupied" problem in the upper right corner may be unexpected

In the `shell` pane, do you see the elvish shell? If you do and the shell works, that message can be safely ignored.

**Comment by jm33-m0** [comment]
And as I recall `!sshd` commands doesn't show up in command history by default (I think it's too noisy so I turned it off). Unless you have set a higher debug level.

**Comment by winezer0** [comment]
> In the `shell` pane, do you see the elvish shell? If you do and the shell works, that message can be safely ignored.

[root@www ~]# elvish
-bash: elvish: command not found
[root@www ~]#

like this？

**Comment by winezer0** [comment]
> And as I recall `!sshd` commands doesn't show up in command history by default (I think it's too noisy so I turned it off). Unless you have set a higher debug level (or using an older version)

I don't know  how to set up the log,  but now I can clear the intermediate windows command record with the  "clear" command

**Comment by winezer0** [comment]
> No, if you look at the tmux panes, right below the command input pane there's a pane titled `Shell`. Do you see a shell in it?

![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/8c1cb28d-c034-450b-b4f2-55b4e88c406e)

YES， There is a "shell"  title in the lower left corner

**Comment by jm33-m0** [comment]
> YES， There is a "shell" title in the lower left corner

Thanks for confirming this. Then it will be safe to ignore the `port occupied` warning.
