### ISSUE TITLE
Different clients are online, but the index is the same

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#236]
# Describe the bug

Different clients are online, but the index is the same

ike in this picture， I have no way to manipulate another host through target 1

# To Reproduce

Normal on-line logic,

Online client 1 with index 1
Online client 2 with index 1，BUG BUG BUG

# Expected behavior

Different client programs go online, should be different index numbers,

# Screenshots

![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/00cbebb6-76a1-43ec-b332-ae63d529a14c)

## CC

Linux distro name and version, use `cat /etc/*release*` to view, paste the result below

```bash
# cat /etc/*release*
```
CentOS Linux release 7.5.1804 (Core)

## C2 Transport

-   [*] Direct connection

### OS

-   [x] Linux

### CPU architecture

-   [x] amd64

# Additional context

1、How do I delete the target of an index 

2、Is the target being selected displayed in green ?

**Comment by jm33-m0** [comment]
Thank you for reporting this.

Currently you can switch to different targets using `target <index>` or `target hostname`. Press <kbd>TAB</kbd> to complete the names.

I will look into the indexing bug soon.

> How do I delete the target of an index

Not possible as of now.

> Is the target being selected displayed in green ?

Yes, and it should be put in the top of the list, which in your case is not. Did you use the latest release?

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/emp3r0r/commit/e6219c5ab86505259076d230ec6b02e864e5a163

This should partially solve this issue and multi-threading safe. To use it, you need to clone this repo and `./emp3r0r --release` to compile yourself.

I will improve the indexing feature in the next release.

**Comment by winezer0** [comment]
Okay, thank you so much. You're really good

**Comment by jm33-m0** [comment]
![image](https://github.com/jm33-m0/emp3r0r/assets/10167884/ccd5a8cc-42cf-44a4-9c97-261cfc99681f)

@winezer0 This indexing issue should be fixed in [v1.30.5](https://github.com/jm33-m0/emp3r0r/releases/tag/v1.30.5)
