### ISSUE TITLE
socks5 agent functionality always crashes, and crashes cause agents to be taken offline,

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#245]
# Describe the bug

socks5 agent functionality always crashes, and crashes cause agents to be taken offline,

# To Reproduce

1. linux running agent
2. Enable the proxy function
3. Try to connect to socks5
4. The link is successful, but the agent network is disconnected
5. panic occurs on the panel
6. PS -ef kills the emp3r0r process and restarts the EMP3R0r process
7. Restart to discover that the agent is offline
8. The agent running on the crashed host cannot go online | Other hosts are normal.

# Expected behavior

1.socks5 needs to be stable, and the agent cannot easily exit by error

2.Can the host run multiple clients at the same time

# Screenshots

No screenshots this time, I forgot every time

# Your environment

## `emp3r0r.json`

I suggest that you format your JSON with an online JSON formatter,
for example [https://codebeautify.org/jsonviewer](https://codebeautify.org/jsonviewer)

<details>
<summary><code>emp3r0r.json</code>:</summary><br>
<pre>
Paste emp3r0r.json here, you can redact sensitive information
</pre>
</details>

## CC

Linux distro name and version, use `cat /etc/*release*` to view, paste the result below

```bash
# cat /etc/*release*
```

## C2 Transport

-   [ ] Direct connection
-   [ ] CDN proxy
-   [ ] Shadowsocks
-   [ ] Shadowsocks + KCP
-   [ ] TOR
-   [ ] Other proxies
-   [ ] None of the above (Please specify blow)

### OS

-   [ ] Linux
-   [ ] Windows

### CPU architecture

-   [ ] amd64
-   [ ] 386
-   [ ] arm
-   [ ] arm64
-   [ ] mips
-   [ ] mips64
-   [ ] riscv64

# Additional context

**Comment by jm33-m0** [comment]
I have tested `run_proxy` feature and it didn't crash.

<img width="875" alt="2023-08-10_14-23" src="https://github.com/jm33-m0/emp3r0r/assets/10167884/0d29a0e6-71e6-4728-96b5-01b950e40e6d">

Could you share the crash log with `VERBOSE=true ./agent`?

**Comment by winezer0** [comment]
Now that I don't have the environment to replicate this,

Can only submit the next time there is a problem

But I guess the problem is caused by too much traffic

Does this command "VERBOSE=true ./agent" run under agent?

Does emp3r0r server have log ?

**Comment by jm33-m0** [comment]
> Does this command "VERBOSE=true ./agent" run under agent?

Yes, it makes agent process print log on stderr

> Does emp3r0r server have log ?

You can type `debug 3` to increase debug level, but mostly it's unnecessary.

**Comment by winezer0** [comment]
Ok, I'll keep an eye on this error message next time.

Usually s5 or other issues (like I broke while generating agent) will indicate that the panel is dead and the entire program must be shut down.

So I can only set the log information before running the program.

**Comment by jm33-m0** [comment]
If you want to cleanly shutdown C2 program, execute `tmux kill-session -t emp3r0r`

**Comment by winezer0** [comment]
> tmux kill-session -t emp3r0

Okay, thank you. That's very helpful.

Oh, and I have a little question

How do I copy the contents of a tmux with emp3r0r installed using my mouse
