### ISSUE TITLE
Unable to use interactive shell in windows7 agent

### ISSUE THREAD

**Issue by heheda123123** [jm33-m0/emp3r0r#253]
# Describe the bug

win7上线之后，在交互式shell窗口中无法输入
其中还有一些报错信息
貌似还乱码了
# To Reproduce

# Expected behavior

# Screenshots

![image](https://github.com/jm33-m0/emp3r0r/assets/97490782/6b9d6cf8-034a-4f18-be2b-a0f920ad779c)

# Your environment

use default config.

## CC

use the latest kali 

## C2 Transport

-   [x] Direct connection
-   [ ] CDN proxy
-   [ ] Shadowsocks
-   [ ] Shadowsocks + KCP
-   [ ] TOR
-   [ ] Other proxies
-   [ ] None of the above (Please specify blow)

### OS

-   [ ] Linux
-   [x] Windows

### CPU architecture

-   [x] amd64
-   [ ] 386
-   [ ] arm
-   [ ] arm64
-   [ ] mips
-   [ ] mips64
-   [ ] riscv64

# Additional context

**Comment by jm33-m0** [comment]
This looks like a bug of upstream project [winpty](https://github.com/rprichard/winpty), which is not actively maintained (last commit was in 2018 and tons of open issues/PRs). Unfortunately winpty is the only feasible option to get interactive shell experience on Windows hosts, the other option is to pipe through [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/releases/latest) and requires additional binaries to be shipped.

**Comment by jm33-m0** [comment]
It's a bug in `elvsh` shell, which doesn't support Windows 7. I will disable shell pane in future releases, if you need to use an interactive shell, please `use interactive_shell` and set `shell` to `cmd.exe` or `powershell.exe` and it will work.

**Comment by jm33-m0** [comment]
The reason to disable shell pane is simple: we don't want to open a shell every time we interact with the target host, that will be too alarming. `elvsh` is basically implemented in emp3r0r itself so it will hide better than `cmd.exe`.
