### ISSUE TITLE
在执行gen_agent的过程中无法退出

### ISSUE THREAD

**Issue by heheda123123** [jm33-m0/emp3r0r#254]
# Describe the bug

如图，执行gen_agent之后不想继续生成了，想退出，但是按C-c并不能终止gen_agent的执行

# To Reproduce

# Expected behavior

结束gen_agent

# Screenshots

![image](https://github.com/jm33-m0/emp3r0r/assets/97490782/073cb82e-3679-4897-b9cd-10405021ce3c)

# Your environment
默认环境

## C2 Transport

-   [ ] Direct connection
-   [ ] CDN proxy
-   [ ] Shadowsocks
-   [ ] Shadowsocks + KCP
-   [ ] TOR
-   [ ] Other proxies
-   [ ] None of the above (Please specify blow)

### OS

-   [ ] Linux
-   [ ] Windows

### CPU architecture

-   [ ] amd64
-   [ ] 386
-   [ ] arm
-   [ ] arm64
-   [ ] mips
-   [ ] mips64
-   [ ] riscv64

# Additional context

**Comment by jm33-m0** [comment]
This design is to prevent unintended interruption. But as you experienced, there should be a way to exit the process and go back to command prompt. I will add <kbd>Ctrl</kbd>+<kbd>c</kbd> as a keybinding to interrupt `gen_agent` in future releases.

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/emp3r0r/commit/a9f36743fcc4c2c8e5085f9318c335280eb361fd

Please test this commit and report anything that you think needs to be worked on.
