### ISSUE TITLE
win7上线之后cpu占用率很高

### ISSUE THREAD

**Issue by heheda123123** [jm33-m0/emp3r0r#255]
# Describe the bug

如图

# To Reproduce

# Expected behavior

没有任何操作的时候应该cpu占用很低

# Screenshots

![image](https://github.com/jm33-m0/emp3r0r/assets/97490782/ae73c0a8-fc20-43d1-a2c2-bde5e51b875b)

# Your environment

默认配置

## CC

kali

## C2 Transport

-   [x] Direct connection
-   [ ] CDN proxy
-   [ ] Shadowsocks
-   [ ] Shadowsocks + KCP
-   [ ] TOR
-   [ ] Other proxies
-   [ ] None of the above (Please specify blow)

### OS

-   [ ] Linux
-   [x] Windows

### CPU architecture

-   [x] amd64
-   [ ] 386
-   [ ] arm
-   [ ] arm64
-   [ ] mips
-   [ ] mips64
-   [ ] riscv64

# Additional context

**Comment by jm33-m0** [comment]
I didn't test it in Windows 7, but is it the same in Windows 10+? Or is it Windows 7 specific?

**Comment by jm33-m0** [comment]
Looks fine from my test, CPU usage is near zero when idle.

![image](https://github.com/jm33-m0/emp3r0r/assets/10167884/68bb402a-e9fe-49c8-ba4b-9c6a75f8e3c8)
