### ISSUE TITLE
kali上使用get_persistence 无效且会报错

### ISSUE THREAD

**Issue by heheda123123** [jm33-m0/emp3r0r#256]
# Describe the bug

最新版kali，上线kali自己，然后像截图那样使用 get_persistence 模块
新打开一个终端会出现第二个截图那样的错误，而且重启之后并没有上线

# To Reproduce

# Expected behavior

# Screenshots

![image](https://github.com/jm33-m0/emp3r0r/assets/97490782/4c9211f2-192e-4ae4-a834-7e6df9807d43)
报错
![image](https://github.com/jm33-m0/emp3r0r/assets/97490782/dc6bc758-b6a6-44e8-854b-6aebc4b50a56)

# Your environment

## `emp3r0r.json`

默认配置

## CC

latest kali
## C2 Transport

-   [x] Direct connection
-   [ ] CDN proxy
-   [ ] Shadowsocks
-   [ ] Shadowsocks + KCP
-   [ ] TOR
-   [ ] Other proxies
-   [ ] None of the above (Please specify blow)

### OS

-   [x] Linux
-   [ ] Windows

### CPU architecture

-   [x] amd64
-   [ ] 386
-   [ ] arm
-   [ ] arm64
-   [ ] mips
-   [ ] mips64
-   [ ] riscv64

# Additional context

**Comment by jm33-m0** [comment]
Thanks for reporting this. Looks like some bug in shell profile, I will look into it when I have time.

**Comment by jm33-m0** [comment]
Fixed by #260
