### ISSUE TITLE
Quiet mode Agent with configurable Beacon timer

### ISSUE THREAD

**Issue by mutexspin** [jm33-m0/emp3r0r#268]
Agent with quiet mode would be useful. Right now(v1.32.1) its noisy, CC Indicator seems to be connecting to msftncsi, even when configured with N while generating agent. Default should be quiet agent that just connects directly to CC, with no other activity.

Configurable timer for agent beacon to CC would be very useful. Agent connects to CC every Timeout period, only acts if there is any commands  queued up for the agent. This could help keep the agent quiet most of the time. Is CC Indicator supposed to behave exactly this way?
 
Also CC Indicator doesn't seem to connect to the custom configured URL, but instead follows the default msftncsi URL always.

Agent Generation could be a seperate app or a command line option of emp3r0r. Presently gen_agent has too many queries, which i often seem to fail at reading the use cached config part and no way to abort midway through.  (maybe even better to remove the Use cached config query, and cached config is offered as default while asking for config; user can just press enter to use default config).
Would be easier to correct/abort if it is seperate app/cmdline. Gonna use seperate shell(in a tmux window) to deliver the agent anyway, so could be easier as seperate app.

**Comment by jm33-m0** [comment]
Thanks for the suggestions. I will explain how "quiet mode" or "CC indicator" works, hopefully it will answer your question.

> CC Indicator seems to be connecting to msftncsi

If you see it constantly connecting to msftncsi, it means the agent is unable to access internet, thus it tries until it gets connectivity.

> Is CC Indicator supposed to behave exactly this way?

Exactly, presumably your C2 is outside of the target network (ie. the Internet), it needs to get Internet access before trying to test the "CC indicator".

> Configurable timer for agent beacon to CC would be very useful

It is, and it's configurable:

https://github.com/jm33-m0/emp3r0r/blob/ed44c96f15b3c00d3d91b6ae902ac9f1f6f530cd/core/lib/data/config.go#L57

**Comment by jm33-m0** [comment]
> Agent Generation could be a separate app or a command line option of emp3r0r

I will add a command line option similar to Sliver's. It will be like `gen_agent -foo bar`. Hope it will address the usability concern.

**Comment by jm33-m0** [comment]
This issue will be closed if no one cares to submit a PR. I am keeping `gen_agent` as is since I personally don't think a cmdline option will be necessary.
