### ISSUE TITLE
v1.32.1 If  run get_root fails, the client exits 

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#269]
![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/852b5b05-cfdd-4b84-9064-04b94ddaa42c)

v1.32.1 If  run get_root fails, the client exits 

Can you set up extra processes to get root

**Comment by jm33-m0** [comment]
Duplicate of #250 

I will reopen #250 and close this one
