### ISSUE TITLE
Failed when install

### ISSUE THREAD

**Issue by starfork** [jm33-m0/emp3r0r#273]
# Describe the bug
`
"cp: cannot stat 'stub*': No such file or directory" when run command 
`
 

`sudo ./emp3r0r --install`
 

 it seems caused by  variables 
`
line 25 :    build_dir="$data_dir/build"

line 28 temp=/tmp/emp3r0r-build
`
in file `emp3r0r` ?

**Comment by jm33-m0** [comment]
> it seems caused by variables

No it's not

> "cp: cannot stat 'stub*': No such file or directory" when run command 

That's because you didn't follow the wiki

I will close this issue since it's invalid
