### ISSUE TITLE
Can I generate an agent in dll format

### ISSUE THREAD

**Issue by fullfill13** [jm33-m0/emp3r0r#292]
Currently only able to generate windows agent in exe format, is it possible to add functionality?

**Comment by jm33-m0** [comment]
This is not supported. However, there's project called [exe_to_dll](https://github.com/hasherezade/exe_to_dll) that might work.

**Comment by fullfill13** [comment]
Thanks, but the converted dll file doesn't work!

**Comment by jm33-m0** [comment]
Building agent as shared library is possible in Windows, I will implement it if I have time to work on it.

**Comment by fullfill13** [comment]
Maybe I can merge main_windows.go and  buildAgent.go into  a C.go file , and compile it as a dll file, but that's too difficult

**Comment by jm33-m0** [comment]
The biggest issue here is cross-building agent as DLL on Linux is quite impossible, perhaps it's an issue with Go itself (and the error is hard to debug).

My plan is to build a DLL stub (just like the exe), and add an option in `gen_agent` so it can be configured for use.

Maybe you can build the DLL on Windows with this command:

```
CGO_ENABLED=1 go build -buildmode=c-shared main_windows.go
```

And in `main_windows.go`, export the `main` function:


```go
import "C"
//export main
func main() {}
```

**Comment by jm33-m0** [comment]
This should work.

![image](https://github.com/jm33-m0/emp3r0r/assets/10167884/a015ae14-5749-42b6-bb97-642c56ba145a)

**Comment by fullfill13** [comment]
and the dll is  a DLL stub , Will buildAgent.go work with this stub?

**Comment by jm33-m0** [comment]
> i can generate main_windows and main_windows.h ，but not dll. May need to keep compiling?
https://merlin-c2.readthedocs.io/en/latest/agent/dll.html

It's merlin-c2, which uses a very different approach to generate DLL. It won't work here. Have you tested the method I just posted?

> and the dll is a DLL stub , Will buildAgent.go work with this stub?

Yes it will.

**Comment by fullfill13** [comment]
I generated the stub dll file, but the last generated is still an exe, which is generated by buildAgent.go, I simply changed the suffix to dll, but then there is no export function, how do I start the dll?

**Comment by fullfill13** [comment]
the stub dll has main export, but the final file does not have it

**Comment by jm33-m0** [comment]
> I simply changed the suffix to dll

Executable and shared library are two different things, changing file names don't change the file.

> the stub dll has main export, but the final file does not have it

Why would it have exported functions? It's still an exe.

Right now the whole thing is being experimented on, it's not implemented so you won't be able to use emp3r0r to generate any DLLs.

**Comment by jm33-m0** [comment]
Can you just wait until this feature is implemented?

**Comment by fullfill13** [comment]
Of course, and I'm going to try it

**Comment by jm33-m0** [comment]
![image](https://github.com/jm33-m0/emp3r0r/assets/10167884/9dce5640-9913-4e0e-ac5a-5e41c4e553dd)

Now the DLL seems to be working, I will test it further and fix the bugs.

**Comment by fullfill13** [comment]
> working

it's cool

**Comment by fullfill13** [comment]
Why is the export function missing after the buildagent.go function reads the stub data, replaces some of the data and rewrites it?

**Comment by jm33-m0** [comment]
It's not done yet. Right now I can only say the DLL **file** is working, agent configuration is not.

**Comment by jm33-m0** [comment]
@fullfill13

![2024-01-30_15-00](https://github.com/jm33-m0/emp3r0r/assets/10167884/cf2c7f86-235e-4681-9262-e658d53c3fb1)

**Comment by jm33-m0** [comment]
Here's the documentation: https://github.com/jm33-m0/emp3r0r/wiki/DLL-Agent
