### ISSUE TITLE
Why would a linux agent be considered a virus and a windows version of the agent not be？

### ISSUE THREAD

**Issue by fullfill13** [jm33-m0/emp3r0r#302]
![image](https://github.com/jm33-m0/emp3r0r/assets/140383365/b4ab7fd4-8a3b-4a66-bd21-13fdcf9a3b67)

**Comment by jm33-m0** [comment]
Since anti-virus is not a concern for most Linux hosts, it's okay if your anti-virus on Windows kills the Linux agent.

Bypassing anti-virus is not in the scope of C2 dev, given the source code you should be able to modify it to bypass AVs easily.
