### ISSUE TITLE
在新版本的target面板下，是否已删除交互shell窗口？

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#306]
在新版本（v1.34.10.tar 及 之后版本）的target面板下，是不是默认不会再显示交互shell窗口了？

（注：以前同样的测试环境是可以显示交互面板信息的）

![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/1d2d14b5-3bfd-42b1-b8e4-1a5956c6d8d1)

提示 错误信息
SFTPClient: Start sshd (elvsh) failed: 
Error: sshd failed to start: listen tcp: address tcp/--: unknown port                                        
Error: listen tcp: address tcp/--: unknown port  

交互shell需要手动 use interactive_shell 
![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/403cc058-1e9b-4ab4-814d-a88916cb0632)
![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/a923f69d-e134-44ac-a52f-fdaa206b9565)

**Comment by jm33-m0** [comment]
是的，首页不再显示shell窗口，可以直接在命令行面板进行基本操作。另外unknown port应该是因为你的配置信息与新的版本不兼容导致的，可以修改json配置文件来匹配最新的设置名称。

**Comment by winezer0** [comment]
能不能直接删除，自动生成适配新版本的配置文件？

**Comment by jm33-m0** [comment]
如果没有需要保存的配置，可以直接删除

**Comment by winezer0** [comment]
删除 /root/.emp3r0r/目录后重新安装程序，OK
