### ISSUE TITLE
大佬看下我这个怎么回事

### ISSUE THREAD

**Issue by backs111** [jm33-m0/emp3r0r#307]
安装好之后运行就这样
<img width="1021" alt="Screenshot 2024-03-03 at 01 19 19" src="https://github.com/jm33-m0/emp3r0r/assets/161965365/886a5d57-a805-41a7-8b83-26cfd93dcc7c">

**Comment by backs111** [comment]
我执行了 tmux kill-session和tmux kill-server然后在运行也不行

**Comment by jm33-m0** [comment]
你的tmux版本是多少？根据这个报错大概率是你的tmux版本不支持最新的参数导致的。以及报bug请使用模板以便提供必要的环境信息。
