### ISSUE TITLE
UnlockDownloads: directory 'file-get' does not exist

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#308]
A small bug, 

the program prompt the directory '.emp3r0r/file-get' does not exist.

version v1.36.0.

2024/03/04 02:13:29 UnlockDownloads: open /root/.emp3r0r/file-get/: no such file or directory

![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/c6701b86-8219-461a-8e52-eb527b53f36c)

**Comment by jm33-m0** [comment]
This can be safely ignored. Once there are any downloads available, the directory will be automatically created.

**Comment by winezer0** [comment]
ok
