### ISSUE TITLE
Fatal tmux error: exec tmux: create pane failed: -1 invalid

### ISSUE THREAD

**Issue by realstatus** [jm33-m0/emp3r0r#309]
# Describe the bug

<img width="827" alt="微信截图_20240325155249" src="https://github.com/jm33-m0/emp3r0r/assets/41789399/a6153ddc-3685-46a7-858f-081390a4a6b3">

用的云服务器没有显示屏。

**Comment by jm33-m0** [comment]
Duplicate of #307 

tmux版本过旧
