### ISSUE TITLE
emp3r0r/core/lib/agent/poll.go  HTTPClient is nil 

### ISSUE THREAD

**Issue by MerSna** [jm33-m0/emp3r0r#31]
直接运行agent emp3r0r/core/lib/agent/poll.go:32 报错panic: runtime error: invalid memory address or nil pointer dereference
可以修改emp3r0r/core/lib/agent/def.go:29 为 HTTPClient = &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
	}

**Comment by jm33-m0** [comment]
兄弟，如果是bug的话可以提交PR
