### ISSUE TITLE
Upload Error : no such file or directory   

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#310]
Version  1.36.0

![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/8d4260f5-d777-4c13-b294-fa6fc294ebb8)

**Comment by jm33-m0** [comment]
There's a typo in your path name: `roor` should be `root`

**Comment by jm33-m0** [comment]
If auto-completion is working, you can just press <kbd>TAB</kbd> to complete the path name.

**Comment by winezer0** [comment]
sorry，This is my problem.
