### ISSUE TITLE
v1.37.0 CPU占用异常

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#315]
CPU占用异常  一下子就到100% 了

当前版本 v1.37.0 
当前OS   centos7

上线了5个机器左右，但是存在大量的emp3r0r进程

![Snipaste_2024-04-17_22-57-37](https://github.com/jm33-m0/emp3r0r/assets/46115146/5623b2d9-812f-4608-828c-f20a8c5f52aa)

杀死进程后 直接降低65% CPU占用率

![Snipaste_2024-04-17_22-58-09](https://github.com/jm33-m0/emp3r0r/assets/46115146/92730e0b-bf25-417e-af3f-64e3c74b9c5f)

**Comment by jm33-m0** [comment]
There are a huge amount of `emp3r0r-cat` processes, which might be the reason. I will test it and see if there's anything to fix when I have time. Thanks for reporting.

**Comment by winezer0** [comment]
waiting for you

**Comment by jm33-m0** [comment]
From my test it looked fine, `emp3r0r-cc` has some CPU usage at first when it's creating the archives and it goes back to normal not long after.

**Comment by winezer0** [comment]
![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/1d2ce5a1-7e6e-43c9-94a1-4be2c1faf059)

![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/4457db03-4166-4b40-99a7-50571a59c8a5)

emp3r0r 似乎是为每个agent开了一个进程 emp3r0r-cat 进程，这个内存使用量能优化吗，

**Comment by jm33-m0** [comment]
No, actually every tmux pane has a `emp3r0r-cat` process to display text interface. If your instance has unusual amount of `emp3r0r-cat` processes open you should check if there's anything wrong with your setup.

BTW never use CentOS as it's been deprecated for a long time, and the tmux version is also too old. Please always use the latest stable software available, for example Ubuntu 22.04 / 24.04 LTS.

**Comment by jm33-m0** [comment]
Also if you could, please fix / improve things as you see fit, I will look into your changes and merge them. I don't have much time to spend on this project for now due to heavy workload.

**Comment by winezer0** [comment]
OK, I think I know the cause of the problem, Probably because I'm running multiple shell terminals.

Thank you for the response , I will learn to optimize
