### ISSUE TITLE
请问 tmux下上线target超过10台 面板显示不全怎么处理呢?

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#319]
请问 tmux下上线target超过10台 面板显示不全怎么处理呢?

**Comment by jm33-m0** [comment]
I believe you can use the scroll button of your mouse to view the complete list of connected hosts in tmux.

If that didn't work, you can try <kdb>Ctrl</kdb><kdb>x</kdb> then press <kdb>Enter</kdb>, then arrow keys should be able to move the cursor.

**Comment by winezer0** [comment]
Thank you very much. I succeeded in solving the problem  with ' Ctrl x  + Enter '
