### ISSUE TITLE
tmux usage

### ISSUE THREAD

**Issue by ameygat** [jm33-m0/emp3r0r#321]
# Describe the bug

I am using emp3r0r v1.37.1 which is installed on Kali linux 2023 Q4 version.
I have generated a agent for Windows and ran in Windows 10 VM in network.
When I try to check if it has connected back using command ls_targets the UI get stuck and does not accept any command. (Not event Ctrl+C , exit, etc)

# To Reproduce

start emp3r0r by using command $ emp3r0r

enter command -> ls_targets

# Expected behavior

I think it should show the current targets and give command prompt for next command ??

# Screenshots

![kali-linux-2023 4-vmware-amd64-2024-06-10-19-05-40](https://github.com/jm33-m0/emp3r0r/assets/10447458/076d5f3b-e2ec-43ea-acca-3ac0b710bb0e)

# Your environment
Kali Linux 2023 q 4 buiild
## `emp3r0r.json`

I suggest that you format your JSON with an online JSON formatter,
for example [https://codebeautify.org/jsonviewer](https://codebeautify.org/jsonviewer)

<details>
<summary><code>emp3r0r.json</code>:</summary><br>
<pre>
{
  "cc_port": "43133",
  "autoproxy_port": "61363",
  "autoproxy_timeout": 0,
  "http_listner_port": "16868",
  "password": "cp<redacted>C",
  "shadowsocks_port": "22022",
  "kcp_port": "57623",
  "use_shadowsocks": false,
  "use_kcp": false,
  "disable_ncsi": true,
  "ssh_host_key": "LS<redacted>S0tLQo=",
  "ssh_proxy_port": "61364",
  "sshd_shell_port": "20368",
  "broadcast_port": "11994",
  "broadcast_interval_min": 30,
  "broadcast_interval_max": 0,
  "cc_host": "192.168.73.111",
  "pid_file": "/tmp/ssh-ycFUaLdoQfzA/MQd",
  "cc_indicator": "",
  "indicator_wait_min": 30,
  "indicator_wait_max": 130,
  "indicator_text": "emperor1",
  "ca": "-----BEGIN CERTIFICATE-----\nMIIB<redacted>PQ+A==\n-----END CERTIFICATE-----\n",
  "ca_fingerprint": "8a<redacted>e",
  "c2transport_proxy": "",
  "cdn_proxy": "",
  "doh_server": "",
  "socket": "/tmp/ssh-ycFUaLdoQfzA/stMRnYFBxCVZLzB",
  "agent_root": "/tmp/ssh-ycFUaLdoQfzA",
  "utils_path": "/tmp/ssh-ycFUaLdoQfzA/ZQZ",
  "agent_uuid": "47f50c3e-02e8-49d1-bc2d-f579eaf0166e",
  "agent_tag": "",
  "timeout": 14649
}
</pre>
</details>

## CC

Linux distro name and version, use `cat /etc/*release*` to view, paste the result below

```bash
# cat /etc/*release*

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.4"
VERSION="2023.4"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

## C2 Transport

-   [x] Direct connection
-   [ ] CDN proxy
-   [ ] Shadowsocks
-   [ ] Shadowsocks + KCP
-   [ ] TOR
-   [ ] Other proxies
-   [ ] None of the above (Please specify blow)

### OS

-   [ ] Linux
-   [x] Windows

### CPU architecture

-   [x] amd64
-   [ ] 386
-   [ ] arm
-   [ ] arm64
-   [ ] mips
-   [ ] mips64
-   [ ] riscv64

# Additional context

Pointers to any simple agent generation and connect back tutorial would be helpful. I have tried the Wiki but it just says follow the procedure on screen. Which is not working for me. I have tried to search for tutorial or videos about emp3r0r but nothing available.

**Comment by jm33-m0** [comment]
Thanks for the detailed report. However, it looks like you are not familiar with `tmux` or the terminal user interface in general. For the "hang" issue, basically you are on a different tmux window which is dedicated for `ls_targets` output. To go back to the main tmux window you can just click on the tab name:

![image](https://github.com/jm33-m0/emp3r0r/assets/10167884/dbc261b8-0a5b-4ba7-b495-7991e2c50210)

You can find more about tmux [here](https://github.com/jm33-m0/emp3r0r/wiki/Tmux)

> Pointers to any simple agent generation and connect back tutorial would be helpful. I have tried the Wiki but it just says follow the procedure on screen. Which is not working for me. I have tried to search for tutorial or videos about emp3r0r but nothing available.

I will update the wiki to make it easier to follow.

**Comment by ameygat** [comment]
Thanks a lot , much appreciate the quick response and I will wait for updated Wiki. My agent for Windows does not connect back, I am trying to investigate why. Simple IP to IP connection on same network with two virtual machines.
