### ISSUE TITLE
https://github.com/jm33-m0/emp3r0r.wiki.git

### ISSUE THREAD

**Issue by mrzezoo** [jm33-m0/emp3r0r#323]
# What did you do? (required)

# What did you expect to happen?

# What happened instead?

<details>
<summary><code>Replace me with the actual command you executed</code>Output:</summary><br>
<pre>
Fill this section with command output
</pre>
</details>

# Your environment

## `emp3r0r.json`

I suggest that you format your JSON with an online JSON formatter,
for example [https://codebeautify.org/jsonviewer](https://codebeautify.org/jsonviewer)

<details>
<summary><code>emp3r0r.json</code>:</summary><br>
<pre>
Paste emp3r0r.json here, you can redact sensitive information
</pre>
</details>

## CC

Linux distro name and version, use `cat /etc/*release*` to view, paste the result below

```bash
# cat /etc/*release*
```

## C2 Transport

-   [ ] Direct connection
-   [x] CDN proxy
-   [ ] Shadowsocks
-   [ ] Shadowsocks + KCP
-   [ ] TOR
-   [ ] Other proxies
-   [ ] None of the above (Please specify blow)

### OS

-   [ ] Linux
-   [ ] Windows

### CPU architecture

-   [ ] amd64
-   [ ] 386
-   [ ] arm
-   [ ] arm64
-   [ ] mips
-   [ ] mips64
-   [ ] riscv64

**Comment by jm33-m0** [comment]
What are you trying to do?
