### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by merlinxcy** [jm33-m0/emp3r0r#42]
```
[*] Copying CC keypair to ./build
 Copy ./tls/emp3r0r-cert.pem to ./build
 Copy ./tls/emp3r0r-key.pem to ./build
GO BUILD starts...
# github.com/jm33-m0/emp3r0r/core/lib/cc
../../lib/cc/cmd.go:133:77: undefined: log.Lmsgprefix
GO BUILD ends...
go build failed

```
![image](https://user-images.githubusercontent.com/18378246/122187130-54b39f80-cec1-11eb-81a3-f760e9dad766.png)

**Comment by merlinxcy** [comment]
ok. The golang version should be go1.15

**Comment by jm33-m0** [comment]
Oh I should update `go.mod` to match my current go version, recently I update to 1.16
