### ISSUE TITLE
Error building: missing go dependencies

### ISSUE THREAD

**Issue by h0nus** [jm33-m0/emp3r0r#43]
This is what i get

I have go, tmux and everything needed to install but i don't understand why it won't build.

![image](https://user-images.githubusercontent.com/23401728/124367191-5ae1a400-dc55-11eb-86a6-9ee12cb3572a.png)

Go Version: `go version go1.16.3 linux/amd64`
Py Version: `Python 3.8.5`
OS Version: `Ubuntu 20.04.2 LTS x86_64`

**Comment by jm33-m0** [comment]
As indicated by `go build`, you are missing dependencies, try `go mod tidy` to get started.

**Comment by jm33-m0** [comment]
I have added `go mod tidy` in `build.py`, so it will take care of this issue automatically.
