### ISSUE TITLE
[FEATURE REQ] Reduce IOCs (Indicators of Compromise)

### ISSUE THREAD

**Issue by ryan7n** [jm33-m0/emp3r0r#45]
工具很好用，功能齐全，感谢大佬开源这么好的工具，唯一感觉不足的是妥协指标太多了，有好几个sock文件，也监听了几个端口，这些要是能精简优化一下就完美了

**Comment by jm33-m0** [comment]
感谢建议。目前agent监听端口可通过禁用广播关闭，其它会在未来优化。

**Comment by jm33-m0** [comment]
Now most of the indicators have been randomized, hope it solves this issue, at least partially

**Comment by jm33-m0** [comment]
From [v0.9.43](https://github.com/jm33-m0/emp3r0r/releases/tag/v0.9.43), all files on disk are randomized, edit `build.json` to customize the randomized values (be careful not to break anything since agents depends on those to communicate with C2 and each other)

**Comment by jm33-m0** [comment]
TODO
- [x] Randomize names
- [ ] Use `memfd` to run `vaccine` binaries
- [ ] Encrypt/Obfuscate files on disk

**Comment by jm33-m0** [comment]
From https://github.com/jm33-m0/emp3r0r/commit/dff671d74db6cf7b02f103900e7a5070b627b76f, you can use `loader.so` to load emp3r0r into any process, then execute it using a custom ELF interpreter, so **no new process** will be created, instead, emp3r0r runs inside an existing process such as `sleep`, `bash`

**Comment by jm33-m0** [comment]
Now most IOCs can be avoided by altering runtime config, except the unix socket (randomized as well).

Further protection will be provided by emp3r0r kernel module, closing for now.
