### ISSUE TITLE
Tmux

### ISSUE THREAD

**Issue by xxlimit** [jm33-m0/emp3r0r#47]
Im am currently running Ubuntu 20.04.3 LTS.
This is what happens when I try to run em3r0r.
```
no server running on /tmp/tmux-1000/default
[exited]
```

**Comment by jm33-m0** [comment]
Did you run `./emp3r0r` in a tmux session?
Try manually execute `tmux new -s emp3r0r` to make sure tmux works

**Comment by xxlimit** [comment]
> Did you run `./emp3r0r` in a tmux session? Try manually execute `tmux new -s emp3r0r` to make sure tmux works
It works.

**Comment by xxlimit** [comment]
> Did you run `./emp3r0r` in a tmux session? Try manually execute `tmux new -s emp3r0r` to make sure tmux works
I have no clue how this works.
![image](https://user-images.githubusercontent.com/66466672/142745136-d38cf22e-a7cc-4625-bfd8-d5b0979bc6c5.png)

**Comment by jm33-m0** [comment]
The `emp3r0r` script tries to set up tmux session and then execute the CC server in it.
From your screenshot you can see the tmux session has been configured successfully.

The reason you got "no server running" error from tmux is unclear, try appending `|| echo blah` to each tmux command to find out which command went wrong

**Comment by xxlimit** [comment]
> The `emp3r0r` script tries to set up tmux session and then execute the CC server in it. From your screenshot you can see the tmux session has been configured successfully.
> 
> The reason you got "no server running" error from tmux is unclear, try appending `|| echo blah` to each tmux command to find out which command went wrong

I tried `tmux -f emp3r0r`
and I got this result
![image](https://user-images.githubusercontent.com/66466672/142745853-34dafe01-8623-4eef-8e95-c754b53bd4a9.png)

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/emp3r0r/blob/c7ded6efb79a0bfb584f1063b3d56ebceed91240/core/emp3r0r#L27

`-f` parameter must be put before `new-session` command since it applies to `tmux` base instead of sub-command
