### ISSUE TITLE
Tmux

### ISSUE THREAD

**Issue by xxlimit** [jm33-m0/emp3r0r#48]
You know how it is,
Also note: I did reinstall and retry your update still inst working though.
![image](https://user-images.githubusercontent.com/66466672/142956383-9e852c8b-cee9-4567-b5a7-28b38309c750.png)

**Comment by jm33-m0** [comment]
Where did you get `-f` flag?
Also, you could just comment on #47 since this is still an old issue.
I have tested my script and I can guarantee it works with the current version of tmux.
As a starter, delete everything and clone again.

**Comment by jm33-m0** [comment]
> Where did you get `-f` flag?

Okay, it's added in my last commit, what version of tmux are you using? Mine is the latest available version under Kali

**Comment by jm33-m0** [comment]
Did a search and found `-f` has been around since 2017 or earlier. If the script doesn't work on your side, it's very likely that your tmux is somehow fucked up, consider starting over in a clean environment or don't use the script at all (you can just run `cc` without the wrapper)

**Comment by xxlimit** [comment]
> Did a search and found `-f` has been around since 2017 or earlier. If the script doesn't work on your side, it's very likely that your tmux is somehow fucked up, consider starting over in a clean environment or don't use the script at all (you can just run `cc` without the wrapper)

How do I run it without the wrapper?

**Comment by jm33-m0** [comment]
`./cc`?

**Comment by vandalise** [comment]
whats your discord? add me herod#6763
