### ISSUE TITLE
Dropper: ValueError: Can only assign sequence of same size

### ISSUE THREAD

**Issue by ybdt** [jm33-m0/emp3r0r#50]
when i use "Download an ELF and execute with memfd_create” from ubuntu18.04, there are return the above error
![image](https://user-images.githubusercontent.com/65813455/147884819-87f6e135-44e8-42b1-b310-8c38ea62f761.png)

**Comment by jm33-m0** [comment]
Can you provide steps to reproduce this error? I have just tested `./gen.py memfd_exec` under `dropper` module, no problems found

**Comment by jm33-m0** [comment]
Closing
