### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dsgz1234-sket** [jm33-m0/emp3r0r#9]
```
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# internal/cpu
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
        generate code that can be linked into a shared library
  -trimpath string
        remove prefix from recorded source file paths
# math/bits
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# runtime/internal/atomic
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
        generate code that can be linked into a shared library
  -trimpath string
        remove prefix from recorded source file paths
# runtime/internal/sys
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# unicode/utf8
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# internal/race
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# sync/atomic
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
        generate code that can be linked into a shared library
  -trimpath string
        remove prefix from recorded source file paths
# unicode
```
try to use go 1.12.4 has the same error.
3q.

**Comment by jm33-m0** [comment]
- what does `go version` give?
- did you use `build.py`?

**Comment by jm33-m0** [comment]
https://github.com/jm33-m0/emp3r0r/blob/3498559ebaea32201a0afea8b441a4c04ed05f5c/core/go.mod#L3

if you take a look at `go.mod` file, it says `go 1.13`, but you can try to change it to match your go version

**Comment by dsgz1234-sket** [comment]
go version
go version go1.15.6 linux/amd64

I have change the go.mod go 1.15 but got the same error.
`./build.py cc
Use cached CC address (0.0.0.0)? [Y/n]
 Copy ./tls/emp3r0r-key.pem to ./build
 Copy ./tls/emp3r0r-cert.pem to ./build
GO BUILD starts...
# errors
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# internal/cpu
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
        generate code that can be linked into a shared library
  -trimpath string
        remove prefix from recorded source file paths
# math/bits
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# runtime/internal/atomic
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
        generate code that can be linked into a shared library
  -trimpath string
        remove prefix from recorded source file paths
# runtime/internal/sys
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# unicode/utf8
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# internal/race
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# sync/atomic
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
        generate code that can be linked into a shared library
  -trimpath string
        remove prefix from recorded source file paths
# unicode
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# encoding
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# unicode/utf16
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# crypto/internal/subtle
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# crypto/subtle
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# container/list
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# internal/x/crypto/cryptobyte/asn1
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# internal/nettrace
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# internal/x/crypto/curve25519
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
        generate code that can be linked into a shared library
  -trimpath string
        remove prefix from recorded source file paths
# golang.org/x/sys/internal/unsafeheader
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# github.com/dsnet/compress/bzip2/internal/sais
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# github.com/dsnet/compress/internal
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# github.com/ulikunitz/xz/internal/hash
compile: version "go1.12.4" does not match go tool version "go1.15.6"
# github.com/zcalusic/sysinfo/cpuid
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
        generate code that can be linked into a shared library
  -trimpath string
        remove prefix from recorded source file paths
GO BUILD ends...
go build failed
`

**Comment by jm33-m0** [comment]
well, looks like your might have multiple `go`s installed, and the one `build.py` picks is `go1.12.4`

check your go build environment, i dont think its an issue with emp3r0r

**Comment by dsgz1234-sket** [comment]
Yes,after check GOROOT and GOPATH it has been OK.
