### ISSUE TITLE
Please do not remove support for agentw.

### ISSUE THREAD

**Issue by arschlochnop** [jm33-m0/emp3r0r#94]
emp3r0r is written in golang, with multi-platform support as its special feature.
I'm very sorry to find that support was removed after tag 1.4.1

I hope to continue to support the windows platform,thx.
Originally I wanted to submit agentw `interactive_shell`'s PR.
Suddenly found no agentw directory.

Can I continue to submit code?
Mainly fixes the error of not being able to input with `interactive_shell` on windows.

**Comment by jm33-m0** [comment]
Thanks for your interest. I deleted `agentw` due to incompatibility with redesigned build process, the plan is to make `package agent` cross-platform so there won't be an `agentw` in future versions.

When I am done rewriting that part, I will let you know and then you can send your PR.

**Comment by jm33-m0** [comment]
From [v1.8.0](https://github.com/jm33-m0/emp3r0r/releases/tag/v1.8.0), Windows support is added back. Now platform-specific code are all marked with build flags, making it easier to add new features for different platforms.

**Comment by jm33-m0** [comment]
@arschlochnop `interactive_shell` for Windows should be usable now, except for  #122

**Comment by arschlochnop** [comment]
Great, I will test it in my environment as soon as possible.
